### ISSUE TITLE
大佬 能不能帮忙编译一个树莓派4B的openwrt

### ISSUE THREAD

**Issue by shum-elli** [Maskbugzero/Netkeeper-OpenWrt#1]

**Comment by Maskbugzero** [comment]
你试一下这个[releases](https://github.com/Maskbugzero/Netkeeper-OpenWrt/releases/tag/2022.03.07-1358)

**Comment by shum-elli** [comment]
可以了但是吧 不能识别USB网卡捏  可以连无线的闪讯了！ 好耶  先谢谢大佬了

**Comment by Maskbugzero** [comment]
因为没编译进USB网卡相关的，我再给你编译一份试试

**Comment by Maskbugzero** [comment]
你试试[这一版本](https://github.com/Maskbugzero/Netkeeper-OpenWrt/releases/tag/2022.03.08-0204)的吧
